import Loading from '@/app/loading'
import React, { Suspense } from 'react'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: {
        default: 'About',
        template: '%s | CT-BOX',
    },
    description: "Generated by create next app",
};
const AboutLayout = ({
    children
}: { children: React.ReactNode }) => {
    return (
        <Suspense fallback={<Loading />}>
            {children}
        </Suspense>
    )
}

export default AboutLayout