import Loading from '@/app/loading'
import React, { Suspense } from 'react'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: {
        default: 'Project & Client',
        template: '%s | CT-BOX',
    },
    description: "Generated by create next app",
};
export default function ProjectLayout({
    children
}: { children: React.ReactNode }) {
    return (
        <Suspense fallback={<Loading />}>
            {children}
        </Suspense>
    )
}
