import ComingSoon from '@/components/ComingSoon'
import React from 'react'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: {
        default: 'Applications',
        template: '%s | CT-BOX',
    },
    description: "Generated by create next app",
};
export default function Clients() {
    return (
        <>
            <ComingSoon />
        </>
    )
}
